import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,ArrowRight,Phone,ArrowLeft} from 'lucide-react';
import {useContent} from '../lib/ContentContext.jsx';
import {FAQItem,ContactBanner} from '../components/shared.jsx';
import {GalleryContent} from '../components/MediaGallery.jsx';
import Seo from '../components/Seo.jsx';
const slides=[{image:'20250107_114439-scaled',title:'A bigger presence.',headline:['Signage design,','manufacturing','& installation.'],body:'From a shopfront to a skyline. We bring your brand into the real world.',label:'Building facade signage',position:'center 48%'},{image:'20250224_135111-scaled',title:'Stand out. At any scale.',headline:['Big spaces.','Bigger','possibilities.'],body:'Turn construction boundaries into a bold statement with hoardings and large-scale site branding.',label:'Hoarding & site branding',position:'center'},{image:'3d-17-scaled',title:'Made to light up.',headline:['Your brand,','in a whole','new light.'],body:'Dimensional lettering and illuminated signs that bring your identity to life, day and night.',label:'Illuminated 3D signage',position:'center'}];
export default function HomePage(){const {company,services,faqs,seo,hero:heroCopy}=useContent();const [slide,setSlide]=useState(0);const [active,setActive]=useState(0);const service=services[active];const hero=slides[slide];return <>
 <Seo title={seo.home.title} description={seo.home.description}/>
 <section className="sg-hero" aria-label="Super Graphic signage"><div className="hero-image"><img key={hero.image} src={slide===0&&heroCopy.image?heroCopy.image:'/images/'+hero.image+'.webp'} alt={hero.label+' from Super Graphic’s project gallery'} style={{objectPosition:hero.position}} fetchPriority="high" width="1920" height="1100"/></div><div className="hero-shade"/><div className="container-x hero-content"><div className="hero-kicker"><span/>{heroCopy.kicker}</div><h1>{hero.headline[0]}<br/><span>{hero.headline[1]}</span><br/>{hero.headline[2]}</h1><p className="hero-description">{hero.body}</p><div className="hero-actions"><a className="button button-white" href={'tel:'+company.phone.replace(/\s/g,'')}><Phone size={17}/>Let’s talk signage<ArrowUpRight size={19}/></a><Link className="hero-work" to="/media-gallery">Explore our work<ArrowUpRight size={19}/></Link></div><div className="hero-bottom"><span>Dubai, UAE <span className="hero-since">/ Since 2006</span></span><div className="slide-control"><div className="slide-caption" aria-live="polite"><strong>{hero.title}</strong><span>{hero.label}</span></div><span className="slide-count">0{slide+1} / 03</span><button onClick={()=>setSlide((slide+2)%3)} aria-label="Previous project"><ArrowLeft size={19}/></button><button onClick={()=>setSlide((slide+1)%3)} aria-label="Next project"><ArrowRight size={19}/></button></div></div></div></section>
 <div className="brand-strip"><span>Big ideas.</span><span aria-hidden="true">✳</span><span>Bold signs.</span><span aria-hidden="true">✳</span><span>Lasting impressions.</span><span aria-hidden="true">✳</span><span>Super Graphic.</span><span aria-hidden="true">✳</span></div>
 <section className="section-space services-section"><div className="container-x"><div className="section-top"><h2>Your brand.<br/><span className="magenta">Every dimension.</span></h2><div><p>One team for every way your brand shows up.<br/>Explore our signage and lighting services.</p><Link className="text-link" to="/services">Explore all services<ArrowUpRight size={19}/></Link></div></div><div className="service-explorer"><div className="service-tabs" role="tablist" aria-label="Our services" aria-orientation="vertical">{services.map((s,i)=><button key={s.slug} role="tab" id={'service-tab-'+i} aria-selected={active===i} aria-controls="service-panel" tabIndex={active===i?0:-1} onClick={()=>setActive(i)} onKeyDown={e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?services.length-1:(i+(e.key==='ArrowDown'?1:services.length-1))%services.length;setActive(n);document.getElementById('service-tab-'+n)?.focus()}}}><span>{s.title}</span><ArrowUpRight size={21}/></button>)}</div><div id="service-panel" role="tabpanel" aria-labelledby={'service-tab-'+active} className="service-feature"><img key={service.image} src={service.image} alt={service.title} width="1000" height="750" loading="lazy"/><div><p>{service.short}</p><Link className="round-link" to={'/services/'+service.slug} aria-label={'Explore '+service.title}><ArrowUpRight size={26}/></Link></div></div></div></div></section>
 <section className="work-section section-space"><div className="container-x"><div className="section-top"><h2>Out there.<br/>Making an impression.</h2><div><p>A closer look at the signs, spaces, and<br/>structures in our project gallery.</p><Link className="text-link" to="/media-gallery">View the full gallery<ArrowUpRight size={19}/></Link></div></div><GalleryContent preview/></div></section>
 <section className="about-band"><div className="container-x about-band-inner"><div className="about-band-intro"><p>Super Graphic Advertising LLC</p><h2>Craft.<br/>Character.<br/><span>Since 2006.</span></h2><Link className="text-link" to="/about">Get to know us<ArrowUpRight size={20}/></Link></div><div className="about-band-copy"><h3>Your vision.<br/>Our hands.</h3><p>We’re signage and graphic professionals based in Dubai. We bring design, manufacturing, and installation together to create signs that give your brand a lasting presence.</p><p>From construction hoardings and rooftop lettering to illuminated shopfronts, we care about the details that make the difference.</p><div className="craft-steps"><span>Thoughtful design</span><span>Precise manufacturing</span><span>Professional installation</span></div></div></div></section>
 <section className="section-space"><div className="container-x faq-layout"><div><h2>No design?<br/><span className="magenta">No problem.</span></h2><p>Bring us your idea. Our designers can help you find the right way to make it visible.</p><Link className="text-link" to="/contact">Talk to our team<ArrowUpRight size={19}/></Link></div><div>{faqs.map((f,i)=><FAQItem key={f.q} id={i} {...f}/>)}</div></div></section>
 <ContactBanner/></>}


