import React from 'react';
import {Link,useParams} from 'react-router-dom';
import {ArrowUpRight,Phone,Mail,MapPin,MessageCircle,Check} from 'lucide-react';
import {useContent} from '../lib/ContentContext.jsx';
import {ServiceCard,ContactBanner} from '../components/shared.jsx';
import LeadForm from '../components/LeadForm.jsx';
import Seo from '../components/Seo.jsx';
export const PageHero=({label,title,description})=><section className="page-hero"><div className="container-x"><p>{label}</p><h1>{title}</h1>{description&&<div className="page-intro">{description}</div>}</div></section>;
export function ServicesPage(){const {services,seo}=useContent();return <><Seo {...seo.services}/><PageHero label="What we do" title={<>A sign for every<br/><span>side of your brand.</span></>} description="Design, manufacturing, and installation. Explore our full range of signage and lighting solutions."/><section className="section-space container-x"><div className="services-grid">{services.map(s=><ServiceCard key={s.slug} service={s}/>)}</div></section><ContactBanner/></>}
export function ServiceDetailPage(){const {slug}=useParams();const {services,company}=useContent();const s=services.find(x=>x.slug===slug);if(!s)return <NotFoundPage/>;return <><Seo title={s.title+' — Super Graphic Dubai'} description={s.short}/><section className="service-detail container-x"><div><Link className="text-link" to="/services">← All services</Link><h1>{s.title}</h1><p>{s.description}</p><ul>{s.bullets.map(b=><li key={b}><Check size={18}/>{b}</li>)}</ul><a href={'tel:'+company.phone.replace(/\s/g,'')} className="button"><Phone size={18}/>Discuss your project<ArrowUpRight size={18}/></a><Link className="text-link" to="/quote">Send an enquiry<ArrowUpRight size={18}/></Link></div><img src={s.image} alt={s.title} width="1000" height="1000"/></section><section className="section-space work-section"><div className="container-x"><h2>From idea to installation.</h2><div className="process-grid">{[['Design','We work with your ideas and brand identity to develop the right visual direction.'],['Manufacture','Our team brings your design to life with attention to materials and detail.'],['Install','Professional installation gives your sign its place in the world.']].map(([t,d],i)=><div key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section><ContactBanner/></>}
export function AboutPage(){return <><Seo title="About us — Super Graphic Dubai" description="Signage and graphic professionals in Dubai, designing, manufacturing and installing signs since 2006."/><PageHero label="Meet Super Graphic" title={<>Big on ideas.<br/><span>Precise on details.</span></>} description="Signage and graphic professionals, bringing brands to life since 2006."/><section className="container-x section-space about-layout"><img src="/images/IMG-20250217-WA0089.webp" alt="Crane-assisted building signage installation from Super Graphic’s gallery" width="900" height="1100"/><div><h2>Built around<br/>your brand.</h2><p>Super Graphic Advertising LLC is a signage manufacturing and installation company in Dubai. We provide signage and lighting solutions with a focus on craftsmanship, attention to detail, and competitive pricing.</p><p>Our signage and digital printing services support brands across the UAE and Saudi Arabia. Our work spans hoarding and fence signs, project identification, construction-site branding, unipole signage, building signs, LED displays, and shop fronts. From initial design to final placement, our team helps turn your vision into something people can see.</p><h3>Design. Manufacture. Install.</h3><p>Three connected stages. A consistent focus on your brand.</p><Link to="/services" className="button">Explore our services<ArrowUpRight size={18}/></Link></div></section><ContactBanner/></>}
export function ContactPage(){const {company}=useContent();return <><Seo title="Contact us — Super Graphic Dubai" description="Call Farman Khan on +971 52 553 8190 or visit Super Graphic in Ras Al Khor Industrial Area 2, Dubai."/><PageHero label="Let’s talk" title={<>Your next big idea<br/><span>starts here.</span></>} description="Tell us what you have in mind. We’ll help you find the right signage for your space and brand."/><section className="container-x section-space contact-layout"><div className="contact-details"><a className="contact-call" href={'tel:'+company.phone.replace(/\s/g,'')}><Phone size={22}/><span>Call Farman Khan<strong>{company.phone}</strong></span><ArrowUpRight size={23}/></a><a href={'mailto:'+company.email}><Mail size={22}/><span>Email us<strong>{company.email}</strong></span></a><a href={company.mapUrl} target="_blank" rel="noreferrer"><MapPin size={22}/><span>Find us<strong>{company.address}</strong></span></a><a href={'https://wa.me/'+company.whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={22}/><span>Prefer a message?<strong>Chat on WhatsApp</strong></span></a></div><div className="enquiry-panel"><h2>Tell us about your project.</h2><p>Complete the details below to prepare your enquiry on WhatsApp.</p><LeadForm source="contact"/></div></section></>}
export function QuotePage(){return <><Seo title="Request a quote — Super Graphic Dubai" description="Tell Super Graphic about your signage project."/><PageHero label="Make it happen" title={<>Let’s put your<br/><span>brand out there.</span></>} description="Share your requirements and prepare an enquiry for our team on WhatsApp."/><section className="container-x section-space quote-form"><LeadForm source="quote"/></section></>}
export function NotFoundPage(){return <><Seo title="Page not found — Super Graphic" noindex/><section className="not-found container-x"><p>404</p><h1>This sign points<br/>somewhere else.</h1><p>The page you’re looking for could not be found.</p><Link className="button" to="/">Back to home<ArrowUpRight size={18}/></Link></section></>}

