import React, { useEffect, useState } from 'react';
import { Link, NavLink, useLocation } from 'react-router-dom';
import { ArrowUpRight, Phone, Menu, X, Plus, Minus, MessageCircle } from 'lucide-react';
import { useContent } from '../lib/ContentContext.jsx';
export const Logo=({light=false})=><Link to="/" className="brand" aria-label="Super Graphic home"><img src={light?'/images/Super-Graphic-White.webp':'/super-graphic-logo.webp'} alt="Super Graphic Advertising LLC" width="1024" height="523"/></Link>;
export function Header(){
 const [open,setOpen]=useState(false);const {pathname}=useLocation();const {company}=useContent();
 
 useEffect(()=>{const close=e=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 const links=[['/','Home'],['/services','Services'],['/media-gallery','Our work'],['/about','About us'],['/contact','Contact']];
 return <header key={pathname} className="site-header"><div className="container-x header-inner"><Logo/><nav className="desktop-nav" aria-label="Main navigation">{links.map(([to,label])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)}>{label}</NavLink>)}</nav><a className="button header-call" href={'tel:'+company.phone.replace(/\s/g,'')}><Phone size={16}/>Call the team<ArrowUpRight size={17}/></a><button className="menu-toggle" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="mobile-nav" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<nav id="mobile-nav" className="mobile-nav" aria-label="Mobile navigation">{links.map(([to,label])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)}>{label}<ArrowUpRight size={20}/></NavLink>)}<a href={'tel:'+company.phone.replace(/\s/g,'')}>Call {company.phone}</a></nav>}</header>
}
export const Reveal=({children,className=''})=><div className={className}>{children}</div>;
export const SectionHead=({title,sub})=><div className="section-heading"><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>;
export const ServiceCard=({service})=><Link className="service-card" to={'/services/'+service.slug}><div className="service-photo"><img src={service.image} alt={service.title} loading="lazy" width="900" height="650"/><span><ArrowUpRight size={23}/></span></div><h3>{service.title}</h3><p>{service.short}</p></Link>;
export function FAQItem({q,a,id}){const [open,setOpen]=useState(false);return <div className="faq-item"><h3><button onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls={'faq-'+id}>{q}{open?<Minus size={20}/>:<Plus size={20}/>}</button></h3><div id={'faq-'+id} hidden={!open}><p>{a}</p></div></div>}
export const Ticker=({items=[]})=><div className="brand-strip">{items.map((item,i)=><React.Fragment key={i}><span>{typeof item==='string'?item:item.en}</span><span aria-hidden="true">✳</span></React.Fragment>)}</div>;
export function ContactBanner(){const {company}=useContent();return <section className="contact-banner"><div className="container-x"><div><p>Have a project in mind?</p><h2>Let’s make it<br/>impossible to miss.</h2></div><div className="contact-banner-action"><a className="button button-white" href={'tel:'+company.phone.replace(/\s/g,'')}><Phone size={18}/>Call the team<ArrowUpRight size={18}/></a><a className="banner-number" href={'tel:'+company.phone.replace(/\s/g,'')}>{company.phone}</a><span>Speak with Farman Khan</span></div></div></section>}
export function Footer(){const {company,services}=useContent();return <footer className="site-footer"><div className="container-x footer-grid"><div className="footer-brand"><Logo light/><p>Bringing brands to life.<br/>From the first idea to the final installation.</p><Link className="text-link" to="/about">Meet Super Graphic<ArrowUpRight size={16}/></Link></div><div><h2>What we do</h2>{services.map(s=><Link key={s.slug} to={'/services/'+s.slug}>{s.title}</Link>)}</div><div><h2>Explore</h2><Link to="/media-gallery">Our work</Link><Link to="/about">About us</Link><Link to="/contact">Contact</Link><Link to="/quote">Request a quote</Link></div><div className="footer-contact"><h2>Let’s talk</h2><a href={'tel:'+company.phone.replace(/\s/g,'')}>{company.phone}</a><a href={'mailto:'+company.email}>{company.email}</a><p>{company.address}</p><a href={company.mapUrl} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={15}/></a></div></div><div className="container-x footer-bottom"><span>© {new Date().getFullYear()} Super Graphic Advertising LLC.</span><div><Link to="/privacy">Privacy</Link><Link to="/terms">Website terms</Link><a href="#main">Back to top ↑</a></div></div></footer>}
export function WhatsAppFloat(){const {company}=useContent();return <a className="whatsapp-float" href={'https://wa.me/'+company.whatsapp} target="_blank" rel="noreferrer" aria-label="Chat with Super Graphic on WhatsApp"><MessageCircle size={24}/></a>}
export function ScrollToTop(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo({top:0,behavior:'instant'})},[pathname]);return null}


